sudo: false
language: node_js

node_js:
  - 12

cache:
  directories:
    - $(npm config get prefix)/lib/node_modules

env:
  - DOCS_DEPLOY_BRANCH=master

install:
  - yarn install --frozen-lockfile

before_script:
  - npm install -g codecov

script:
#  - lerna run lint
  - lerna run build
#  - lerna run typecheck
#  - lerna run coverage
#  - lerna run test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote add publish-origin --fetch https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout conventional-test
  - if [[ $TRAVIS_BRANCH = $DOCS_DEPLOY_BRANCH ]]; then
      yarn run demo:build;
    fi

deploy:
  - provider: script
    script: npx lerna publish --conventional-commits --git-remote publish-origin --yes
    skip_cleanup: true
    on:
      branch: conventional-test
      node_js: "12"

#  - provider: npm
#    email: "$NPM_EMAIL"
#    api_key: "$NPM_TOKEN"
#    skip_cleanup: true
#    edge: true
#    on:
#      branch: conventional-test
#      node_js: "10"

#  - provider: pages
#    github-token: "$GITHUB_TOKEN"
#    skip-cleanup: true
#    local-dir: "docs"
#    keep-history: true
#    edge: true
#    on:
#      branch: $DOCS_DEPLOY_BRANCH
#      node_js: "10"

#after_script:
#  - codecov
